name: farmers_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  intl: ^0.19.0
  intl_utils: ^2.8.7
  url_launcher: ^6.3.1
  change_app_package_name: ^1.4.0
  carousel_slider: ^5.0.0
  animated_splash_screen: ^1.3.0
  camera: ^0.11.0+2 # For camera access
  dio: ^5.7.0
  image_picker: ^1.0.7

  flutter_bloc: ^8.1.2 # For state management
  flutter_phoenix: ^1.0.0 # To restart the app programmatically
  get_it: ^7.6.0 # For dependency injection
  flutter_inappwebview: ^6.1.5
  shared_preferences: ^2.0.15 # For local storage

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_intl:
  enabled: true
  arb-dir: lib/l10n
  output-dir: lib/generated
  use-deferred-loading: true # Set true for larger apps with many locales

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
