import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:farmers_app/generated/l10n.dart'; // Assuming you've generated the localization files.

class Agri extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Good Agri Practices',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primaryColor: Colors.green,
        appBarTheme: AppBarTheme(
          backgroundColor: Colors.green,
        ),
      ),
      supportedLocales: S.delegate.supportedLocales,
      localizationsDelegates: [
        S.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      home: Container(
        color: Colors.yellow[500],
        child: Scaffold(
          appBar: AppBar(
            title: Text(S.of(context).goodAgriPractice, style: TextStyle(color: Colors.white)),
            leading: IconButton(
              icon: Icon(Icons.arrow_back), color: Colors.white,
              onPressed: () {
                Navigator.of(context).pop();
              },
            ),
          ),
          body: SingleChildScrollView(
            child: Padding(
              padding: EdgeInsets.all(20),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    S.of(context).generalGuidelines,
                    style: TextStyle(fontWeight: FontWeight.bold),
                  ),
                  SizedBox(height: 10),
                  Text(S.of(context).goodAgriPracticesDescription),
                  SizedBox(height: 10),
                  Text(S.of(context).implementingGAP),
                  SizedBox(height: 10),
                  Text(S.of(context).socialDimension),
                  SizedBox(height: 10),
                  Text(S.of(context).soybeanGuidelines),
                  SizedBox(height: 10),
                  Text(S.of(context).soilManagement, style: TextStyle(fontWeight: FontWeight.bold)),
                  SizedBox(height: 10),
                  Text(S.of(context).soilManagementPoint1),
                  SizedBox(height: 10),
                  Text(S.of(context).soilManagementPoint2),
                  SizedBox(height: 10),
                  Text(S.of(context).soilManagementPoint3),
                  SizedBox(height: 10),
                  Text(S.of(context).soilManagementPoint4),
                  SizedBox(height: 10),
                  Text(S.of(context).soilManagementPoint5),
                  SizedBox(height: 10),
                  Text(S.of(context).soilManagementPoint6),
                  SizedBox(height: 10),
                  Text(S.of(context).seed, style: TextStyle(fontWeight: FontWeight.bold)),
                  SizedBox(height: 10),
                  Text(S.of(context).seedPoint1),
                  SizedBox(height: 10),
                  Text(S.of(context).seedPoint2),
                  SizedBox(height: 10),
                  Text(S.of(context).seedPoint3),
                  SizedBox(height: 10),
                  Text(S.of(context).seedPoint4),
                  SizedBox(height: 10),
                  Text(S.of(context).seedPoint5),
                  SizedBox(height: 10),
                  Text(S.of(context).fertilizerUse, style: TextStyle(fontWeight: FontWeight.bold)),
                  SizedBox(height: 10),
                  Text(S.of(context).fertilizerPoint1),
                  SizedBox(height: 10),
                  Text(S.of(context).fertilizerPoint2),
                  SizedBox(height: 10),
                  Text(S.of(context).fertilizerPoint3),
                  SizedBox(height: 10),
                  Text(S.of(context).fertilizerPoint4),
                  SizedBox(height: 10),
                  Text(S.of(context).planting, style: TextStyle(fontWeight: FontWeight.bold)),
                  SizedBox(height: 10),
                  Text(S.of(context).plantingPoint1),
                  SizedBox(height: 10),
                  Text(S.of(context).plantingPoint2),
                  SizedBox(height: 10),
                  Text(S.of(context).plantingPoint3),
                  SizedBox(height: 10),
                  Text(S.of(context).plantingPoint4),
                  SizedBox(height: 10),
                  Text(S.of(context).pestAndDiseaseManagement, style: TextStyle(fontWeight: FontWeight.bold)),
                  SizedBox(height: 10),
                  Text(S.of(context).pestPoint1),
                  SizedBox(height: 10),
                  Text(S.of(context).pestPoint2),
                  SizedBox(height: 10),
                  Text(S.of(context).pestPoint3),
                  SizedBox(height: 10),
                  Text(S.of(context).pestPoint4),
                  SizedBox(height: 10),
                  Text(S.of(context).pestPoint5),
                  SizedBox(height: 10),
                  Text(S.of(context).pesticideUse, style: TextStyle(fontWeight: FontWeight.bold)),
                  SizedBox(height: 10),
                  Text(S.of(context).pesticidePoint1),
                  SizedBox(height: 10),
                  Text(S.of(context).pesticidePoint2),
                  SizedBox(height: 10),
                  Text(S.of(context).pesticidePoint3),
                  SizedBox(height: 10),
                  Text(S.of(context).pesticidePoint4),
                  SizedBox(height: 10),
                  Text(S.of(context).pesticidePoint5),
                  SizedBox(height: 10),
                  Text(S.of(context).pesticidePoint6),
                  SizedBox(height: 10),
                  Text(S.of(context).irrigation, style: TextStyle(fontWeight: FontWeight.bold)),
                  SizedBox(height: 10),
                  Text(S.of(context).irrigationPoint1),
                  SizedBox(height: 10),
                  Text(S.of(context).irrigationPoint2),
                  SizedBox(height: 10),
                  Text(S.of(context).irrigationPoint3),
                  SizedBox(height: 10),
                  Text(S.of(context).irrigationPoint4),
                  SizedBox(height: 10),
                  Text(S.of(context).harvestingAndPostHarvesting, style: TextStyle(fontWeight: FontWeight.bold)),
                  SizedBox(height: 10),
                  Text(S.of(context).harvestingPoint1),
                  SizedBox(height: 10),
                  Text(S.of(context).harvestingPoint2),
                  SizedBox(height: 10),
                  Text(S.of(context).harvestingPoint3),
                  SizedBox(height: 10),
                  Text(S.of(context).harvestingPoint4),
                  SizedBox(height: 10),
                  Text(S.of(context).copyright, style: TextStyle(fontWeight: FontWeight.bold)),
                  SizedBox(height: 10),

                  // Continue with the rest of your sections
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
